# Generated by Django 4.2.6 on 2023-12-02 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bundle_name', models.CharField(max_length=50, unique=True)),
                ('bundle_price', models.CharField(max_length=50)),
                ('bundle_data', models.CharField(max_length=6)),
                ('bundle_data_type', models.CharField(max_length=3)),
                ('bundle_duration', models.CharField(max_length=50)),
                ('bundle_duration_type', models.CharField(choices=[('Days', 'Days'), ('Months', 'Months')], max_length=15)),
                ('bundle_type', models.CharField(choices=[('Home', 'Home'), ('Classic', 'Classic'), ('Premium', 'Premium')], max_length=15)),
                ('bundle_limitted', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('telephone_one', models.CharField(max_length=50, unique=True)),
                ('telephone_two', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=7, null=True, unique=True)),
                ('barcode', models.ImageField(blank=True, upload_to='images/')),
                ('qrcode', models.ImageField(blank=True, upload_to='images/')),
                ('alt_text', models.CharField(blank=True, max_length=50, null=True)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('bundle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_bundle', to='billing.bundle')),
            ],
        ),
    ]
